version : "3.7"
services :
 mysqldb:
  image: mysql
  restart: unless-stopped
  env_file: ./.env
  ports: 
   - 3307:3306
  environment:
   - MYSQL_DATABASE=root
   - MYSQL_ROOT_PASSWORD=root
  volumes:
   - db:/var/lib/mysql
 app:
  depends_on:
   - mysqldb
  image: emnatoumi/achat
  build:
   context: "./"
   dockerfile: "Dockerfile"
  restart: on-failure
  env_file: ./.env
  ports: 
   - 8000-8999:8088
  volumes:
   - .m2:/root/.m2
  environment:
   SPRING_APPLICATION_JSON: '{
    "spring.datasource.url"  : "jdbc:mysql://192.168.33.10:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
    "spring.datasource.username" : "root",
    "spring.datasource.password" : "root",
    "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
    "spring.jpa.hibernate.ddl-auto" : "update"
       }'