version : "3"
services :
 mysql2:
  image: mysql2
  restart: unless-stopped
  ports: 
   - 3307:3306
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=achat
   - MYSQL_USER=ghofran
   - MYSQL_PASSWORD=root
  volumes:
   - db1:/var/lib/mysql2
 mysql3:
  image: mysql3
  restart: unless-stopped
  ports: 
   - 3307:3306
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=achatTest
   - MYSQL_USER=ghofran
   - MYSQL_PASSWORD=root
  volumes:
   - db2:/var/lib/mysql3
 app:
  depends_on:
   - mysql2
  image: ghofran24/achatProject
  build:
   context: "./"
   dockerfile: "Dockerfile"
  restart: on-failure
  ports: 
   - 8000-8999:8088
  volumes:
   - .m2:/root/.m2
  environment:
   SPRING_APPLICATION_JSON: '{
    "spring.datasource.url"  : "jdbc:mysql://192.168.33.10:3306/achat?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
    "spring.datasource.username" : "ghofran",
    "spring.datasource.password" : "root",
    "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
    "spring.jpa.hibernate.ddl-auto" : "update"
       }'
 test:
  depends_on:
   - mysql3
  image: ghofran24/achatProject
  profiles: ["tester"]
  build:
   context: "./"
   dockerfile: "Dockerfile"
  restart: on-failure
  ports: 
   - 8000-8999:8088
  volumes:
   - .m2:/root/.m2
  environment:
   SPRING_APPLICATION_JSON: '{
    "spring.datasource.url"  : "jdbc:mysql://192.168.33.10:3306/achatTest?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
    "spring.datasource.username" : "ghofran",
    "spring.datasource.password" : "root",
    "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
    "spring.jpa.hibernate.ddl-auto" : "update"
       }'
volumes:
 db1:
 db2: