version: '3'
services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    ports:
      - 3306:3306

  spring-boot:
    image: chaimabenammar/springproject
    container_name: spring
    ports:
      - 8089:8089
    depends_on:
      - database