version: '3.7'

services:

  mysql-db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - dbachat:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: wiemabada/backend:43
    ports:
      - "8089:8089"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/achatdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
volumes:
  dbachat: