version : "3"
services :
 mysqldb:
  image: mysql:latest
  restart: unless-stopped
  ports: 
   - 3306:3307
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_USER=root
   - MYSQL_PASSWORD=root
  volumes:
   - db:/var/lib/mysql2
 app:
  depends_on:
   - mysqldb
  image: ghofran24/achat:64
  build:
   context: "./"
   dockerfile: "Dockerfile"
  restart: on-failure
  ports: 
   - 8000-8999:8087
  volumes:
   - .m2:/root/.m2
  environment:
   SPRING_APPLICATION_JSON: '{
    "spring.datasource.url"  : "jdbc:mysql://192.168.33.10:3306/achat?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
    "spring.datasource.username" : "root",
    "spring.datasource.password" : "root",
    "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
    "spring.jpa.hibernate.ddl-auto" : "update"
       }'
 test:
  depends_on:
   - mysqldb
  image: ghofran24/achat:64
  build:
   context: "./"
   dockerfile: "Dockerfile"
  restart: on-failure
  ports: 
   - 8000-8999:8088
  volumes:
   - .m2:/root/.m2
  environment:
   SPRING_APPLICATION_JSON: '{
    "spring.datasource.url"  : "jdbc:mysql://192.168.33.10:3306/achatTest?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
    "spring.datasource.username" : "root",
    "spring.datasource.password" : "root",
    "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
    "spring.jpa.hibernate.ddl-auto" : "update"
       }'
volumes:
 db:
